### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by eestein** [richlander/dependabot-dotnet-test-projects#15]
@richlander I'm sorry to open this issue here, but I didn't know how else to get in touch with you.

I'm a long time Xamarin developer (since 2013) and a C# developer for even longer. Since 2016 I'm a software architect and helped to develop the company's SDK (built with .net core, currently v5) used by some 50 devs. Now, we're deciding between flutter and xamarin (maui) for our next mobile projects. Because of that, I'm digging deep into the subject, and that's how I found your comment here:

https://github.com/dotnet/maui/issues/160#issuecomment-649811389

In my research I did find that flutter uses skia, but I couldn't find information backing up your claim that it's only a rendering engine. I do agree (obviously) that xamarin is an abstraction, but I couldn't find information to corroborate your comment regarding flutter.

Would you mind sharing that with me, please?
Also, if you have any more information that you think might be helpful in my decision, I'd appreciate it.
I did read a lot already, but who knows :)

I appreciate you taking the time to answer me.

Kind regards,
Eros Stein

**Comment by richlander** [comment]
This seems to cover it: https://flutter.dev/docs/resources/faq#what-makes-flutter-unique

**Comment by eestein** [comment]
@richlander thank you!
